---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess.default $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R webroot $DEPLOYPATH
    - /bin/cp -R plugins $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
